name: Tracking Version

on:
  schedule:
    - cron: "0 6,14,22 * * *"
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: tracking version
        run: curl https://telebot-open-source-tracking-version.vercel.app/api/tracking
